defmodule HighSociety.Tournaments.Regions do
  @moduledoc """
  Country/state/province reference data for the tournament registration
  form's KYC section (`HighSociety.Tournaments.PokerTournamentEntry`).
  The State field only makes sense as a constrained dropdown for the
  three North American countries most entrants come from - everywhere
  else it stays a free-text "Region" field (see
  `HighSocietyWeb.TournamentLive`).

  `@countries` excludes the countries under comprehensive OFAC sanctions
  (Cuba, Iran, North Korea, Syria) as of this writing - this is a
  UX-level gate on the dropdown itself, not a substitute for the real
  sanctions/blacklist screening described in `PokerTournamentEntry`'s
  moduledoc, which still has to happen manually before any prize payout.
  Sanctions programs change over time, so this list should be revisited
  periodically rather than treated as permanently accurate.
  """

  # {stored value, display label} - same convention as
  # HighSociety.Support.Report's @categories/@games. US/CA/MX come first
  # since they're the three with a constrained State dropdown (see
  # `state_options_for/1`); everything else is alphabetical by name.
  @countries [
    {"US", "United States"},
    {"CA", "Canada"},
    {"MX", "Mexico"},
    {"AF", "Afghanistan"},
    {"AL", "Albania"},
    {"DZ", "Algeria"},
    {"AD", "Andorra"},
    {"AO", "Angola"},
    {"AG", "Antigua and Barbuda"},
    {"AR", "Argentina"},
    {"AM", "Armenia"},
    {"AU", "Australia"},
    {"AT", "Austria"},
    {"AZ", "Azerbaijan"},
    {"BS", "Bahamas"},
    {"BH", "Bahrain"},
    {"BD", "Bangladesh"},
    {"BB", "Barbados"},
    {"BY", "Belarus"},
    {"BE", "Belgium"},
    {"BZ", "Belize"},
    {"BJ", "Benin"},
    {"BT", "Bhutan"},
    {"BO", "Bolivia"},
    {"BA", "Bosnia and Herzegovina"},
    {"BW", "Botswana"},
    {"BR", "Brazil"},
    {"BN", "Brunei"},
    {"BG", "Bulgaria"},
    {"BF", "Burkina Faso"},
    {"BI", "Burundi"},
    {"CV", "Cabo Verde"},
    {"KH", "Cambodia"},
    {"CM", "Cameroon"},
    {"CF", "Central African Republic"},
    {"TD", "Chad"},
    {"CL", "Chile"},
    {"CN", "China"},
    {"CO", "Colombia"},
    {"KM", "Comoros"},
    {"CG", "Congo-Brazzaville"},
    {"CD", "Congo-Kinshasa"},
    {"CR", "Costa Rica"},
    {"CI", "Côte d'Ivoire"},
    {"HR", "Croatia"},
    {"CY", "Cyprus"},
    {"CZ", "Czech Republic"},
    {"DK", "Denmark"},
    {"DJ", "Djibouti"},
    {"DM", "Dominica"},
    {"DO", "Dominican Republic"},
    {"EC", "Ecuador"},
    {"EG", "Egypt"},
    {"SV", "El Salvador"},
    {"GQ", "Equatorial Guinea"},
    {"ER", "Eritrea"},
    {"EE", "Estonia"},
    {"SZ", "Eswatini"},
    {"ET", "Ethiopia"},
    {"FJ", "Fiji"},
    {"FI", "Finland"},
    {"FR", "France"},
    {"GA", "Gabon"},
    {"GM", "Gambia"},
    {"GE", "Georgia"},
    {"DE", "Germany"},
    {"GH", "Ghana"},
    {"GR", "Greece"},
    {"GD", "Grenada"},
    {"GT", "Guatemala"},
    {"GN", "Guinea"},
    {"GW", "Guinea-Bissau"},
    {"GY", "Guyana"},
    {"HT", "Haiti"},
    {"HN", "Honduras"},
    {"HK", "Hong Kong"},
    {"HU", "Hungary"},
    {"IS", "Iceland"},
    {"IN", "India"},
    {"ID", "Indonesia"},
    {"IQ", "Iraq"},
    {"IE", "Ireland"},
    {"IL", "Israel"},
    {"IT", "Italy"},
    {"JM", "Jamaica"},
    {"JP", "Japan"},
    {"JO", "Jordan"},
    {"KZ", "Kazakhstan"},
    {"KE", "Kenya"},
    {"KI", "Kiribati"},
    {"KW", "Kuwait"},
    {"KG", "Kyrgyzstan"},
    {"LA", "Laos"},
    {"LV", "Latvia"},
    {"LB", "Lebanon"},
    {"LS", "Lesotho"},
    {"LR", "Liberia"},
    {"LY", "Libya"},
    {"LI", "Liechtenstein"},
    {"LT", "Lithuania"},
    {"LU", "Luxembourg"},
    {"MG", "Madagascar"},
    {"MW", "Malawi"},
    {"MY", "Malaysia"},
    {"MV", "Maldives"},
    {"ML", "Mali"},
    {"MT", "Malta"},
    {"MH", "Marshall Islands"},
    {"MR", "Mauritania"},
    {"MU", "Mauritius"},
    {"FM", "Micronesia"},
    {"MD", "Moldova"},
    {"MC", "Monaco"},
    {"MN", "Mongolia"},
    {"ME", "Montenegro"},
    {"MA", "Morocco"},
    {"MZ", "Mozambique"},
    {"MM", "Myanmar"},
    {"NA", "Namibia"},
    {"NR", "Nauru"},
    {"NP", "Nepal"},
    {"NL", "Netherlands"},
    {"NZ", "New Zealand"},
    {"NI", "Nicaragua"},
    {"NE", "Niger"},
    {"NG", "Nigeria"},
    {"MK", "North Macedonia"},
    {"NO", "Norway"},
    {"OM", "Oman"},
    {"PK", "Pakistan"},
    {"PW", "Palau"},
    {"PS", "Palestine"},
    {"PA", "Panama"},
    {"PG", "Papua New Guinea"},
    {"PY", "Paraguay"},
    {"PE", "Peru"},
    {"PH", "Philippines"},
    {"PL", "Poland"},
    {"PT", "Portugal"},
    {"QA", "Qatar"},
    {"RO", "Romania"},
    {"RU", "Russia"},
    {"RW", "Rwanda"},
    {"KN", "Saint Kitts and Nevis"},
    {"LC", "Saint Lucia"},
    {"VC", "Saint Vincent and the Grenadines"},
    {"WS", "Samoa"},
    {"SM", "San Marino"},
    {"ST", "Sao Tome and Principe"},
    {"SA", "Saudi Arabia"},
    {"SN", "Senegal"},
    {"RS", "Serbia"},
    {"SC", "Seychelles"},
    {"SL", "Sierra Leone"},
    {"SG", "Singapore"},
    {"SK", "Slovakia"},
    {"SI", "Slovenia"},
    {"SB", "Solomon Islands"},
    {"SO", "Somalia"},
    {"ZA", "South Africa"},
    {"KR", "South Korea"},
    {"SS", "South Sudan"},
    {"ES", "Spain"},
    {"LK", "Sri Lanka"},
    {"SD", "Sudan"},
    {"SR", "Suriname"},
    {"SE", "Sweden"},
    {"CH", "Switzerland"},
    {"TW", "Taiwan"},
    {"TJ", "Tajikistan"},
    {"TZ", "Tanzania"},
    {"TH", "Thailand"},
    {"TL", "Timor-Leste"},
    {"TG", "Togo"},
    {"TO", "Tonga"},
    {"TT", "Trinidad and Tobago"},
    {"TN", "Tunisia"},
    {"TR", "Turkey"},
    {"TM", "Turkmenistan"},
    {"TV", "Tuvalu"},
    {"UG", "Uganda"},
    {"UA", "Ukraine"},
    {"AE", "United Arab Emirates"},
    {"GB", "United Kingdom"},
    {"UY", "Uruguay"},
    {"UZ", "Uzbekistan"},
    {"VU", "Vanuatu"},
    {"VA", "Vatican City"},
    {"VE", "Venezuela"},
    {"VN", "Vietnam"},
    {"YE", "Yemen"},
    {"ZM", "Zambia"},
    {"ZW", "Zimbabwe"},
    {"OTHER", "Other"}
  ]

  @us_states [
    {"AL", "Alabama"},
    {"AK", "Alaska"},
    {"AZ", "Arizona"},
    {"AR", "Arkansas"},
    {"CA", "California"},
    {"CO", "Colorado"},
    {"CT", "Connecticut"},
    {"DE", "Delaware"},
    {"DC", "District of Columbia"},
    {"FL", "Florida"},
    {"GA", "Georgia"},
    {"HI", "Hawaii"},
    {"ID", "Idaho"},
    {"IL", "Illinois"},
    {"IN", "Indiana"},
    {"IA", "Iowa"},
    {"KS", "Kansas"},
    {"KY", "Kentucky"},
    {"LA", "Louisiana"},
    {"ME", "Maine"},
    {"MD", "Maryland"},
    {"MA", "Massachusetts"},
    {"MI", "Michigan"},
    {"MN", "Minnesota"},
    {"MS", "Mississippi"},
    {"MO", "Missouri"},
    {"MT", "Montana"},
    {"NE", "Nebraska"},
    {"NV", "Nevada"},
    {"NH", "New Hampshire"},
    {"NJ", "New Jersey"},
    {"NM", "New Mexico"},
    {"NY", "New York"},
    {"NC", "North Carolina"},
    {"ND", "North Dakota"},
    {"OH", "Ohio"},
    {"OK", "Oklahoma"},
    {"OR", "Oregon"},
    {"PA", "Pennsylvania"},
    {"RI", "Rhode Island"},
    {"SC", "South Carolina"},
    {"SD", "South Dakota"},
    {"TN", "Tennessee"},
    {"TX", "Texas"},
    {"UT", "Utah"},
    {"VT", "Vermont"},
    {"VA", "Virginia"},
    {"WA", "Washington"},
    {"WV", "West Virginia"},
    {"WI", "Wisconsin"},
    {"WY", "Wyoming"}
  ]

  @ca_provinces [
    {"AB", "Alberta"},
    {"BC", "British Columbia"},
    {"MB", "Manitoba"},
    {"NB", "New Brunswick"},
    {"NL", "Newfoundland and Labrador"},
    {"NS", "Nova Scotia"},
    {"NT", "Northwest Territories"},
    {"NU", "Nunavut"},
    {"ON", "Ontario"},
    {"PE", "Prince Edward Island"},
    {"QC", "Quebec"},
    {"SK", "Saskatchewan"},
    {"YT", "Yukon"}
  ]

  @mx_states [
    {"AGU", "Aguascalientes"},
    {"BCN", "Baja California"},
    {"BCS", "Baja California Sur"},
    {"CAM", "Campeche"},
    {"CHP", "Chiapas"},
    {"CHH", "Chihuahua"},
    {"CMX", "Ciudad de México"},
    {"COA", "Coahuila"},
    {"COL", "Colima"},
    {"DUR", "Durango"},
    {"GUA", "Guanajuato"},
    {"GRO", "Guerrero"},
    {"HID", "Hidalgo"},
    {"JAL", "Jalisco"},
    {"MEX", "México"},
    {"MIC", "Michoacán"},
    {"MOR", "Morelos"},
    {"NAY", "Nayarit"},
    {"NLE", "Nuevo León"},
    {"OAX", "Oaxaca"},
    {"PUE", "Puebla"},
    {"QUE", "Querétaro"},
    {"ROO", "Quintana Roo"},
    {"SLP", "San Luis Potosí"},
    {"SIN", "Sinaloa"},
    {"SON", "Sonora"},
    {"TAB", "Tabasco"},
    {"TAM", "Tamaulipas"},
    {"TLA", "Tlaxcala"},
    {"VER", "Veracruz"},
    {"YUC", "Yucatán"},
    {"ZAC", "Zacatecas"}
  ]

  @doc "The `{value, label}` options for the form's country select."
  def country_options, do: @countries

  @doc """
  The `{value, label}` state/province options for a given country code,
  or `nil` if that country doesn't have a constrained list (in which
  case State stays a free-text field).
  """
  def state_options_for("US"), do: @us_states
  def state_options_for("CA"), do: @ca_provinces
  def state_options_for("MX"), do: @mx_states
  def state_options_for(_country), do: nil

  @doc "The field label to show above the State dropdown for a given country code."
  def state_field_label("CA"), do: "Province"
  def state_field_label(_country), do: "State"
end
